### ISSUE TITLE
"fluree.crypto.sha3.node$module$js_sha3.sha3 is not a function"

### ISSUE THREAD

**Issue by marco3479** [fluree/fluree.crypto#22]
I am using the @fluree/flureenjs v^1.0.5 library for node js on pre-prod env, and fluree.crypto is the dependency causing an error as follows. I'm trying to transact a signed transaction with a private key:

```js
export async function transact(tx) {
  const flureenjs = await import('@fluree/flureenjs');
  const flureeServerUrl = "http://localhost:8090";
  const conn = await flureenjs.connect(flureeServerUrl);
  const pvK = "PRIVATE_KEY";
  const auth = "TexM4h4Fx6Gdv6XCNbZiJyZR7BAsuYAQyzK";

  const options = {
    "private-key": pvK,
    auth: auth,
    expire: Date.now() + 30000,
    timeout: 600000,
  }

  try {
    const resp = await flureenjs.transact(conn, FLUREE_NETWORK.LEDGER, tx, options);
    flureenjs.close(conn);
    return await resp.json();
  } catch (err) {
    console.error("ERROR", err);
  }
}
```

===================

*tx* function errors `fluree.crypto.sha3.node$module$js_sha3.sha3 is not a function`.
After checking the [js_sha3 library](https://www.npmjs.com/package/js-sha3) I can't find the *sha3* function either. There are other similar functions, like *shake128*, but not *sha3*.
Currently I can't find a workaround if I want to sign the transaction.

Thanks in advance. 
Best,

Marco Mongalo

**Comment by cap10morgan** [comment]
Thank you for reporting this @marco3479! Sorry it took so long to address. I added some tests, confirmed they fail in the way you describe, and then fixed the code in PR #24. Hoping to land that soon, roll a release, and then do a new release of the [db lib](https://github.com/fluree/db) that includes this fix.

**Comment by cap10morgan** [comment]
This fix is included in the 1.0.0 release of this library and in the 3.0.0-alpha2 release of the [fluree/db library](https://github.com/fluree/db).
